### PR TITLE
Handle no docs gracefully

### LINKED ISSUE #57: HydraResource.operations blows up when ApiDocumentation is missing
### Actual behaviour
When there is no ApiDocumentation and I access the property `operations` on a `HydrarResource`, alcaeus fails with: `TypeError: Cannot read property 'getOperations' of undefined`.

### Expected behaviour
When there is no ApiDocumentation and I access the property `operations` on a `HydrarResource`, alcaeus either 
* returns null and logs a warning 
* throws a named error with an appropriate message.

### Notes
As a newcomer this shows that an API has to implement ApiDocumentation in order to conform to Hydra.

### PR DESCRIPTION
**Pull request by tpluscode**
fixes #57

### CODE REVIEW

File: src/support/Maybe.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
+/**
+ * Maybe monad inspired by https://codewithstyle.info/advanced-functional-programming-in-typescript-maybe-monad/
+ */
+export class Maybe<T> {
```
Comment (jerben) [inline src/support/Maybe.ts]: @tpluscode Have you considered being compatible with https://github.com/cbowdon/TsMonad/blob/master/src/maybe.ts?
